[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"
RUSTUP_TOOLCHAIN = "nightly"

[build]
# for demo or preview
command = "npx pnpm i --no-frozen-lockfile --store=node_modules/.pnpm-store && npx pnpm run build:pre"
publish = "dist"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
